### ISSUE TITLE
Save playlist order

### ISSUE THREAD

**Issue by d33pcode** [streambinder/spotitube#29]
When the `-playlist` option is requested, save the tracks order in a `m3u` playlist file.
This will let users easily import playlists with their favourite music player.

**Comment by d33pcode** [comment]
If in doubt, the format should be something like that:
```m3u
#EXTM3U
#EXTINF:207432,Arctic Monkeys - Arabella
~/Music/Arctic Monkeys - Arabella.mp3
#EXTINF:162960,Black Pistol Fire - Suffocation Blues
~/Music/Black Pistol Fire - Suffocation Blues.mp3
#EXTINF:134922,Dick Dale and his Del-Tones - Misirlou
~/Music/Dick Dale and his Del-Tones - Misirlou.mp3
```
Where:
- `#EXTM3U` is the file header
- the next lines that start with `#EXTINF:` are in the form `$track_length_seconds, $artist_name - $song_title`
- after each line that starts with `#EXTINF:` there must be a line containing the full path of the file.

**Comment by streambinder** [comment]
Approved, thank you for your hint and help.
Just one thing: [_m3u_](https://en.wikipedia.org/wiki/M3U) it should allow to use relative path to the songs filenames, not only absolute ones. Writing those files this way should allow users to use always the same file on every platform they're actually on.

**Comment by d33pcode** [comment]
*m3u* is actually a *de facto* standard; it doesn't care about how you write the song's path because it's just a string that the media players read.
As far as I know, all players support relative paths; so, your only problem is about the platform compatibility. 
You can save `playlistname.m3u` in the `-folder` path and specify each song's path as `./songtitle.mp3`. Unfortunately, I don't know how media players behave when it comes to opening the "playlist file" (maybe it translates relative paths to absolutes?), nor what happens if you move song files from one folder to another.
You should test it by yourself 😉

**Comment by d33pcode** [comment]
I've noticed the song is written in the m3u file even if the download fails.
Can you fix this?

**Comment by streambinder** [comment]
Thank you.
