### ISSUE TITLE
Problem right after authenticating

### ISSUE THREAD

**Issue by manuelbuil** [streambinder/spotitube#31]
After executing:
`spotitube -folder Music/ -log`

I get a message in a window of my firefox browser saying: Login completed. However, right after that, there is a problem:

```
[2018-01-26 17:15:33] Something went wrong while fetching album info: Something gone wrong in 0th chunk [[]] of albums: invalid id..
```

Any idea what might be the problem?

**Comment by streambinder** [comment]
Got it. Already encountered in few cases.
Expect an update in the weekend.
