### ISSUE TITLE
Something went wrong while fetching playlist info

### ISSUE THREAD

**Issue by manuelbuil** [streambinder/spotitube#32]
It authenticates correctly but when it tries to fetch the playlist fails. I was trying with one of my playlist and I also tried with the example you have in the gif:

`/usr/local/sbin/spotitube -folder Music/ -playlist spotify:user:'Davide Pucci':playlist:TMG`

Both with the same result

**Comment by streambinder** [comment]
To fetch playlist you should specify playlist URI provided by spotify client itself.
These are the steps I take to get it:
![screen1](https://user-images.githubusercontent.com/7783188/35564300-ff65c6a8-05b9-11e8-9f3f-502fab8e09a9.png)
![screen2](https://user-images.githubusercontent.com/7783188/35564301-ff7d5aac-05b9-11e8-8841-4e1d60016db3.png)

An example playlist URI is this one: `spotify:user:streambinder:playlist:3XYT6FdGxx9XrmdVLsUaoy` (which is perfectly working by my side).

If you still have errors, please, execute the same command appending `-debug -log` flags, and then attach `spotitube-*.log` generated file here.
