### ISSUE TITLE
Problem authenticating using latest version

### ISSUE THREAD

**Issue by manuelbuil** [streambinder/spotitube#33]
I pulled the latest code and when authenticating, my browser opens a tab with a lot of HTML text: https://hastebin.com/carisobeya.xml

Then it fails with:
```
runtime error: index out of range
goroutine 1 [running]: 
    panic(0x83c24c0, 0x1892a028)    /usr/lib64/go/src/runtime/panic.go:500 +0x331
    spotify.(*Spotify).ParsePlaylistUri(0x1892a708, 0xffb05148, 0x24, 0xffb05156, 0x16, 0x0, 0x0)    /home/manuel/spotitube/src/spotify/spotify.go:149 +0xd6
    spotify.(*Spotify).Playlist(0x1892a708, 0xffb05148, 0x24, 0x80, 0x0, 0x0)    /home/manuel/spotitube/src/spotify/spotify.go:81 +0x3f
    main.main()    /home/manuel/spotitube/src/main/main.go:226 +0x70ab
```

**Comment by streambinder** [comment]
Can you please paste here the command you actually executed to encounter the issue?

**Comment by manuelbuil** [comment]
My bad! I was trying an album instead of a playlist. I guess that is wrong:

spotitube -folder Music/ -playlist spotify:user:telecolega:playlist:7pZiWmgTehd66MBCSOQx4e

**Comment by streambinder** [comment]
Yup, downloading albums is not supported yet. Maybe I'll add that feature, too.
Marking as closed.
