### ISSUE TITLE
Spotify playlist fetch failure, web browser shows raw markup

### ISSUE THREAD

**Issue by SajeOne** [streambinder/spotitube#34]
Not sure why this happens but when spotitube opens a browser page it shows markup but doesn't actually render it. Results in spotitube saying "Something went wrong while fetching playlist info".
![Bug](https://shane-brown.ca/img/b57cc72.png)

**Comment by streambinder** [comment]
Hi. Few questions:

1. Are you using released v14 or one built by yourself?
2. Would you paste the command you executed to face the error?
3. Which Chromium browser version are you using? I tried to replicate the issue with the `67.0.3396.79` without experiencing any issue at all.

**Comment by SajeOne** [comment]
1. I cloned and built the current master branch
2. `./spotitube -playlist 6cZAySbWMXKioRBSqWsYxF`
3. Using version 67.0.3396.87

If I'm not logged in through spotify it lets me login when the webpage opens but then just dumps this markup.

**Comment by SajeOne** [comment]
Had the same issue with that new -playlist argument so I built from the v14 tag and now I'm getting:
![Invalid redirect uri](https://shane-brown.ca/img/77aad0d.png)

**Comment by streambinder** [comment]
Ok, got it. Which `SPOTIFY_KEY` are you exporting while building?

**Comment by SajeOne** [comment]
I'm using a client secret from one of my personal apps. I also just tried creating a fresh keypair through the developer section and still the same result.

**Comment by streambinder** [comment]
Are you sure you're using both your app ID and KEY during build process?
Also, that `Invalid redirect URI` makes me think about an eventual mismatch between the callback URI passed from SpotiTube and the one set in the settings page of your app dashboard.
I actually have set `http://localhost:8080/callback` as callback URI, and that URI is the one SpotiTube opens HTTP socket for.

**Comment by SajeOne** [comment]
Just added the callback and it's working fine now. Thanks for the help, any chance of adding that callback to the README?
