### ISSUE TITLE
Cannot build "extra characters at the end of p command"

### ISSUE THREAD

**Issue by dislick** [streambinder/spotitube#36]
I am trying to build this application on macOS 10.13.6. This is the error I receive:

```
λ ~/r/spotitube/ master SPOTIFY_ID=my_id SPOTIFY_KEY=my_key make

WARNING: GENIUS_TOKEN environment variable is not set. You won't be able to fetch Genius lyrics.
-en Building...
sed: 1: "/Users/myname/r/sp ...": extra characters at the end of p command
mv: rename /Users/myname/r/spotitube/src/track/constant.go.orig to /Users/myname/r/spotitube/src/track/constant.go: No such file or directory
make: *** [bin] Error 1
```

Any ideas what could be wrong?

**Comment by streambinder** [comment]
It seems to be due to the fact MacOS' `sed` command handles input flag differently if compared to GNU' one.
I just made a commit to add Darwin platform as supported: update the repository and retry. Let me know.

**Comment by dislick** [comment]
Thanks, I was able to build it now.
