### ISSUE TITLE
CLIENT_INVALID error

### ISSUE THREAD

**Issue by UmutAlihan** [streambinder/spotitube#38]
Trying to validate using the tiny url provided by the app.

Even though I am on the correct machine, it throws CLIENT_INVALID error.

I have created my own app and gave the api keys while compiling.

What am I missing, or what causes this error?

Great app anyway, Thank you,

**Comment by streambinder** [comment]
`CLIENT_INVALID` error should actually mean there's a mismatch on client credentials (`ID` or `secret`).
Are you sure you used the right ones?
You should find them in your application dashboad, at developer.spotify.com, as in the following example:

![screen](https://user-images.githubusercontent.com/7783188/45300708-621ced80-b50f-11e8-8bae-9618d45fa95e.png)

**Comment by streambinder** [comment]
No feedback received. Closing.
