### ISSUE TITLE
Authentication failing after completing once

### ISSUE THREAD

**Issue by johngough** [streambinder/spotitube#43]
Running on Mac (Mojave 10.14.3), built from .bin

I had trouble getting authentication redirect to work, but once I successfully authenticated, spotitube continues to tell me "Unable to authenticate to spotify" in both GUI and headless.

The log file shows that it's returning "Authentication completed." afterward, but it's not progressing to a download state.

Screenshot: http://s.skybox1.com/9VHLzb

I'm using command: `./spotitube -folder ~/Music -playlist spotify:user:jhgough:playlist:52STzrIiqvc7Z8EP0JW2oW -disable-gui -log -debug`

(Global command doesn't work - not found, I had to chmod -x the main file)

Log:
```
WARNING: Unknown GENIUS_TOKEN: please, export SPOTIFY_KEY enviroment variable, if you wan't to fetch lyrics from Genius provider.
Folder: ~/Music
Log: spotitube_2019-05-15_15.37.56.log
Version: 24
Caller: installed
Date: 2019-05-15 15:37:56
URL: https://github.com/streambinder/spotitube
License: GPLv2
Version youtube-dl: 2019.05.11
Version ffmpeg: 4.1.3
Actual version 24, online version 24.
// I removed index here //

Authentication URL: http://tinyurl.com/y64ems4r
Waiting for automatic login process. If wait is too long, manually open that URL.
Unable to authenticate to spotify.
Authentication completed.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2db58d]

goroutine 1 [running]:
github.com/zmb3/spotify.(*Client).CurrentUser(0x0, 0x0, 0x3b2500, 0x11d460a0)
	/Users/johngough/Desktop/spotitube/src/github.com/zmb3/spotify/user.go:87 +0x2d
spotify.(*Spotify).User(0x11d46190, 0x43991d, 0x19, 0x80, 0x0)
	/Users/johngough/Desktop/spotitube/src/spotify/interface.go:79 +0x1d
main.mainFetch()
	/Users/johngough/Desktop/spotitube/src/main/main.go:229 +0x167
main.main()
	/Users/johngough/Desktop/spotitube/src/main/main.go:215 +0x10bb
```

**Comment by streambinder** [comment]
Are you trying to trying to both run spotitube and authenticate on browser on the same machine?
Can you please upload here your log?

**Comment by johngough** [comment]
Yes, using the same machine.

Thanks!

[Logfile](http://s.skybox1.com/r2f2iW)

**Comment by streambinder** [comment]
Can you please retry building upstream version? It includes bunch of fixes.
Let me know.

**Comment by streambinder** [comment]
Closing due to missing feedback.
