### ISSUE TITLE
Downloading playlist containing local file(s)

### ISSUE THREAD

**Issue by ckhawks** [streambinder/spotitube#44]
I tried to download both a playlist with only a local file and a playlist with local file + normal Spotify song and it states
```
[2019-05-20 09:01:23] Version youtube-dl: 2019.05.11
[2019-05-20 09:01:23] Version ffmpeg: 3.4.6
[2019-05-20 09:01:23] Outside authentication enabled: assure "spotitube.local" points to this machine.
[2019-05-20 09:01:23] Indexing started...
[2019-05-20 09:01:24] Indexing finished: 3 tracks indexed and 3 linked.
[2019-05-20 09:01:25] Authentication URL: http://tinyurl.com/y4tekybq
[2019-05-20 09:01:30] Authentication completed.
[2019-05-20 09:01:30] Session user: meltedexistence
[2019-05-20 09:01:30] Fetching playlist data...
[2019-05-20 09:01:30] Something went wrong while fetching playlist info.
```

Using `./spotitube.bin -authenticate-outside -folder /downloads -playlist https://open.spotify.com/user/meltedexistence/playlist/1PYnNE4ZzwFxVM07v4wfbT?si=_eIN2hk5QhiMLvvP4btRTQ -disable-playlist-file -log` as my command. There is no log file in the spotitube directory.

**Comment by streambinder** [comment]
> There is no log file in the spotitube directory.

It seems you actually found where the log was (other issue hints :)), would you please be so kind to replace the issue body code with the dump of the log file?

**Comment by ckhawks** [comment]
Replaced! Let me know if you want me to try anything else. I doubt you'll actually be able to download local files as they're sadly only accessible on the computer they are uploaded from and hack-ily through mobile devices. It would just be nice if it could detect they were there and ignore them. Thanks!

**Comment by streambinder** [comment]
Thank you.
Yup, my intention is to detect and ignore them, alerting the user about why that happened and incrementing an additional counter (such as for `duplicates` / `missing` ).

**Comment by streambinder** [comment]
I'm waiting for this PR to be merged: https://github.com/zmb3/spotify/pull/93 .
Once done there, this issue will be almost solved.

**Comment by streambinder** [comment]
Please, test this binary. It includes the https://github.com/streambinder/spotitube/commit/1ba5c128c59400a48cf6d8f0128ec063556ee618 fix: 
[spotitube.txt](https://github.com/streambinder/spotitube/files/3199484/spotitube.txt).
Let me know.
