### ISSUE TITLE
SoundCloud as a fallback download provider

### ISSUE THREAD

**Issue by ckhawks** [streambinder/spotitube#47]
One more idea for the night: if the song is not found on YouTube, could it be searched for on SoundCloud? A lot of my songs are failing to be found on YouTube but come up with one SoundCloud search. youtube-dl will still download from SoundCloud :)

**Comment by streambinder** [comment]
Good idea: I never really thought about that as I always considered YouTube the most reliable source for tracks download, but it seems SoundCloud expanded.
Unfortunately API applications are temporarily down so I think I would replicate the same scraping logic used for YouTube (although a proper way to do that should be structuring code to support generic _download providers_ and let YouTube and SoundCloud be the sources of different _download providers_ ).
Thank you, will think about that.

**Comment by streambinder** [comment]
[This commit](https://github.com/streambinder/spotitube/commit/43d0f2eb536757252e4e424bca0b35ac04830cd7) provides the application a new download providers modularization: this means that if anyone is interested in introducing a new provider, he/she'd look at actual [youtube.go](https://github.com/streambinder/spotitube/blob/43d0f2eb536757252e4e424bca0b35ac04830cd7/src/provider/youtube.go) provider implementation and imitate its behaviour.
Probably soon I'll write some documentation notes about that.

Closing this one as at the moment, I won't be that one.
