### ISSUE TITLE
Windows Binary produces this error in a command prompt

### ISSUE THREAD

**Issue by ZachBacon** [streambinder/spotitube#48]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x6b299c]

goroutine 1 [running]:
main.main()
        /home/streambinder/Workspace/spotitube/src/main/main.go:137 +0x87c

**Comment by streambinder** [comment]
Thank you. Next release should already have that fixed.

**Comment by ZachBacon** [comment]
Thanks, I'll keep an eye out on this.

**Comment by streambinder** [comment]
Hi @ZachBacon, I made two new builds for Windows: [spotitube-20200125.zip](https://github.com/streambinder/spotitube/files/4111889/spotitube-20200125.zip)
Can you please test them both for me?
 - `spotitube-20200115-pointer.exe` should just fix the issue you reported.
 - `spotitube-20200115-cui.exe` should add support for console UI interface for windows.

Thank you, let me know.

**Comment by ZachBacon** [comment]
@streambinder The error I get now is just how it executes the default browser 

> Authentication failed: exec: "start": executable file not found in %PATH%,

**Comment by streambinder** [comment]
Ok, @ZachBacon, you can try with this one: [spotitube-20200125-2.zip](https://github.com/streambinder/spotitube/files/4112268/spotitube-20200125-2.zip).

**Comment by ZachBacon** [comment]
@streambinder Getting much closer seems it's missing the redirect, the spotify webpage that spotitube throws at me this error.

> Missing required parameter: redirect_uri

**Comment by streambinder** [comment]
I already tested the entire flow on windows and it's working properly now.
If you want to try yourself, here you have: [spotitube-20200126.zip](https://github.com/streambinder/spotitube/files/4113385/spotitube-20200126.zip).

**Comment by ZachBacon** [comment]
I'm still getting a redirect issue for some reason, But I could of set the keys and ID wrong potentially.

**Comment by streambinder** [comment]
This last binary I gave you has already my keys in it, so you should be using my Spotify application.

Just to be sure, the following one still has my APIs built-in and it's exactly the one I manually tested (and it's working fine in my case): [spotitube-20200126-2.zip](https://github.com/streambinder/spotitube/files/4113402/spotitube-20200126-2.zip)

**Comment by ZachBacon** [comment]
@streambinder Yeah, it was a clash, I'm at the end of the day myself and I'm tired lol

**Comment by streambinder** [comment]
You can confirm it's working, then?

**Comment by ZachBacon** [comment]
I do indeed.
