### ISSUE TITLE
what is GENIUS_TOKEN

### ISSUE THREAD

**Issue by Logan1x** [streambinder/spotitube#50]
I am getting error for setting up genius token. what is this error? looks like it is for lyrics from genius. How can I disable it or get token?

![image](https://user-images.githubusercontent.com/10944610/71762081-c036c680-2ef2-11ea-99a2-b825b9837788.png)

**Comment by Logan1x** [comment]
Solved after creating a new token from https://genius.com/api-clients/new
You might want to add this to docs.

**Comment by Logan1x** [comment]
Feedback: I didn't know how to set up environment variable and setting up in home directory was not working so you might want to also that that how to set that up.

**Comment by streambinder** [comment]
Hi, thank you for the advise. You can export environment variables both for just the single process (look at this: https://doc.davidepucci.it/p/spotitube/installation#passing-spotify-api-credentials) and using the `export` command.
Doc needs a full rewriting as `spotitube` has been hugely revised in the last months.

**Comment by Logan1x** [comment]
Yes export method worked for me and I request you to make an AUR package too for arch Linux based users :)

**Comment by streambinder** [comment]
Open a different issue for that, please.

**Comment by Logan1x** [comment]
Sure
